# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='slug',
            field=models.CharField(default='', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
